services:
  - type: pserv
    name: tor-daemon
    env: docker
    image: osminogin/tor-simple

  - type: pserv
    name: i2pd-daemon
    env: docker
    image: purplei2p/i2pd

  - type: web
    name: daemon-proxy
    env: docker
    plan: free 
    envVars:
      - key: TOR_SOCKS
        value: socks5h://tor-daemon:9050
      - key: I2P_SOCKS
        value: socks5h://i2pd-daemon:4447
